# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170927_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='type',
            field=models.CharField(default=1, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200),
            preserve_default=False,
        ),
    ]
