# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170927_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='Name',
            field=models.CharField(default=1, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=150),
            preserve_default=False,
        ),
    ]
